name: basalt_assessment
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.1

dependencies:
  bloc: ^8.1.0
  connectivity_plus: ^3.0.2
  dartz: ^0.10.0
  dio: ^4.0.6
  equatable: ^2.0.3
  fl_chart: ^0.55.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  json_annotation: ^4.6.0
  logger: ^1.1.0
  relative_scale: ^2.0.0

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.2.0
  flutter_native_splash: ^2.2.7
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Light.ttf
          weight: 200
        - asset: fonts/Inter-ExtraLight.ttf
          weight: 300
        - asset: fonts/Inter-Regular.ttf
          weight: 400
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: fonts/Inter-Black.ttf
          weight: 900
